resend/resend-laravel

- README.md
This PR updates the packagist links to use `resend/laravel`.
> Update README.md to include Laravel package URL

- tests/Facades/Resend.php
This PR improves the tests for the Resend facade. Previously it wasn't tested if the Resend facade would return an instance of `Resend\Client`.
> improve tests for Resend facade

- composer.json
- tests/Transport/ResendTransportFactory.php
This PR updates the Laravel package to use `resend/client` v0.2. This update uses the new `Sent` response class, which was renamed from `EmailSent`.
> Fix tests to support `resend/client` v0.2

- composer.json
- tests/Transport/ResendTransportFactory.php
This PR updates the library to use `resend/resend-php` instead of `resend/client`.
> Update Resend PHP SDK

- README.md
I think when the move to the org was made, `resenlabs` forgot to change the org in the readme.
> chore: readme org name

- README.md
- composer.json
- src/Facades/Resend.php
- tests/Facades/Resend.php
This PR adds a `Resend` facade to the library. This can be useful for accessing the `Resend` client instance in the Laravel container to make API requests to Resend, such as:
```php
use Resend\Laravel\Facades\Resend;
Resend::apiKeys()->list();
Resend::domains()->remove('id');
Resend::emails()->send([...]);
```
> feat: Add Facade to library

- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR ensures that all email address recipient parameters (`to`, `cc`, `bcc`, and `reply_to`) are converted to string arrays before making a API request to Resend.
This PR also adds an additional test that ensures multiple recipients are correctly handled when the API request is made.
Fixes #30
> fix: ensure email address parameters are sent as string arrays

- composer.json
- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR adds support for headers in the Symfony `ResendTransport`. Tests have also been added to ensure headers are correctly sent to the API. The `Resend` Facade can already make use of `headers` in emails.
> feat: add support for headers

- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR will set a `X-Resend-Email-ID` header on the `SentMessage` instance. This allows developers to get the ID of the email that was sent via the Resend API.
> feat: set X-Resend-Email-ID after the email is sent

- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR adds the ability to send `attachments` with your Mailable class to Resend.
With the addition of `base64` encoded attachments, we can now send attachments from Laravel through to Resend.
> feat: Add the ability to include attachments

- composer.json
- src/Http/Controllers/WebhookController.php
- src/Http/Middleware/VerifyWebhookSignature.php
- tests/Http/Controllers/WebhookController.php
- tests/Http/Middleware/VerifyWebhookSignature.php
- tests/Pest.php
This PR adds a `VerifyWebhookSignature` middleware to verify webhook requests to `/resend/webhook` route.
Depends on https://github.com/resendlabs/resend-php/pull/40
> feat: add VerifyWebhookSignature middleware

- .gitattributes
This PR ensures that config and test specific files are not included in an export. An export is usually when composer downloads the library on an application.
> chore: Ignore config files from export

- .github/workflows/tests.yml
This PR adds the test workflow for PHP 8.3. Laravel 9 with PHP 8.3 is excluded.
> feat: Add tests for PHP 8.3

- .github/workflows/tests.yml
- composer.json
This PR adds support for Laravel 11.x and drops support for Laravel 9.x (now considered end of life)
> feat: Add support for Laravel 11

- phpunit.xml
- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR changes the exception from `Exception` to `TransportException` to better identify the type of error that was caused.
> change: Throw TransportException instead of general Exception

- src/Http/Controllers/WebhookController.php
- src/Http/Middleware/VerifyWebhookSignature.php
- src/Transport/ResendTransportFactory.php
- tests/Http/Controllers/WebhookController.php
- tests/Transport/ResendTransportFactory.php
This PR adds the ability to set the mime type for a mailable attachment using the new `content_type` parameter in the Resend email API.
> feat: Add the ability to set attachment mime type

- src/Events/ContactCreated.php
- src/Events/ContactDeleted.php
- src/Events/ContactUpdated.php
- src/Http/Controllers/WebhookController.php
- tests/Http/Controllers/WebhookController.php
This PR adds support for the new Contact related webhook events that were recently released: https://resend.com/changelog/new-contact-webhooks
This PR adds 3 new Laravel events to handle the new events as well as tests.
> feat: Add support for Contact Webhook Events

- src/Events/DomainCreated.php
- src/Events/DomainDeleted.php
- src/Events/DomainUpdated.php
- src/Http/Controllers/WebhookController.php
- tests/Http/Controllers/WebhookController.php
This PR adds support for the new [Domain webhook events](https://resend.com/docs/dashboard/webhooks/event-types#domain-created).
- `domain.created` -> `DomainCreated`
- `domain.deleted` -> `DomainDeleted`
- `domain.updated` -> `DomainUpdated`
> feat: Add support for Domain Webhook Events

- src/Transport/ResendTransportFactory.php
I noticed when using both custom headers and attachments my headers disappeared on the data being sent to the resend API. 
It seems the headers array is being overwritten bij the attachments loop.
> Fix: prevent headers being lost when attachments are added

- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR updates the ResendTrasportFactory to skip encoding of `text/calendar` file attachments. This fixes an issue where ICS files aren't correctly formatted when delivered to an email inbox.
> fix: skip encoding for ICS file attachments

- src/Transport/ResendTransportFactory.php
- tests/Transport/ResendTransportFactory.php
This PR adds support for inline attachments when using the Laravel Mailer. While this is automatically all handled within Laravel this PR simply ensures the correct request parameters are passed for inline attachments.
> feat: add support for inline attachments
